# Project information
site_name: GeoServer
site_description: Designed for interoperability to publishes data from any major spatial data source using open standards.

site_dir: target/html
site_url: https://docs.geoserver.org/

# Repository
repo_name: geoserver
repo_url: https://github.com/geoserver/geoserver
edit_uri: edit/main/docs/en/user/docs

# Copyright
copyright: Copyright &copy; 2023 Open Source Geospatial Foundation

extra_css:
  - assets/stylesheets/extra.css

# Configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/images/geoserver_mark.png
  favicon: assets/images/geoserver_mark.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

# Plugins - install using: pip3 install -r requirements.txt
plugins:
  - exclude:
      glob:
        - '**/*.rst'
        - 'conf.py'
  - include-markdown:
      preserve_includer_indent: true
      dedent: true
      comments: false
  - macros:
      render_by_default: false
      on_error_fail: true
      on_undefined: strict
  - search
  
# Customizations
hooks:
  - download.py
extra:
  homepage: https://geoserver.org/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geoserver
    - icon: geoserver/logo
      link: https://geoserver.org/
      name: GeoServer Home
  version: '2.24'
  release: '2.24.1'

# Extensions
# - These are carefully chosen to work with pandoc markdown support for whole document translation
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - md_in_html
  
# Validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: info
    absolute_links: info
    unrecognized_links: info

# Page tree
not_in_nav: |
  **/download/*.md

nav:
  - 'User Manual': index.md
  - 'Introduction':
    - introduction/index.md
    - introduction/overview.md
    - introduction/history.md
    - introduction/gettinginvolved.md
    - introduction/license.md
  - 'Installation':
    - installation/index.md
    - installation/linux.md
    - installation/win_binary.md
    - installation/win_installer.md
    - installation/war.md
    - installation/docker.md
    - installation/upgrade.md
  - 'Getting Started':
    - gettingstarted/index.md
    - gettingstarted/geopkg-quickstart/index.md
    - gettingstarted/group-quickstart/index.md
    - gettingstarted/image-quickstart/index.md
    - gettingstarted/postgis-quickstart/index.md
    - gettingstarted/shapefile-quickstart/index.md
    - gettingstarted/style-quickstart/index.md
    - gettingstarted/web-admin-quickstart/index.md
  - 'Web Admin':
    - webadmin/index.md
    - webadmin/about.md
    - webadmin/welcome.md
  - 'Data':
    - data/index.md
    - 'Data Settings':
      - data/webadmin/index.md
      - data/webadmin/layergroups.md
      - data/webadmin/layerpreview.md
      - data/webadmin/layers.md
      - data/webadmin/stores.md
      - data/webadmin/workspaces.md
    - 'Vector':  
      - data/vector/index.md
      - data/vector/directory.md
      - data/vector/featurepregen.md
      - data/vector/geopkg.md
      - data/vector/properties.md
      - data/vector/shapefile.md
    - 'Raster':
      - data/raster/index.md
      - data/raster/arcgrid.md
      - data/raster/coverageview.md
      - data/raster/gdal.md
      - data/raster/geopkg.md
      - data/raster/geotiff.md
      - data/raster/imagepyramid.md
      - data/raster/worldimage.md
      - data/raster/imagemosaic/index.md
      - data/raster/imagemosaic/configuration.md
      - data/raster/imagemosaic/tutorial.md
    - 'Database':  
      - data/database/index.md
      - data/database/connection-pooling.md
      - data/database/db2.md
      - data/database/h2.md
      - data/database/jndi.md
      - data/database/mysql.md
      - data/database/oracle.md
      - data/database/postgis.md
      - data/database/primarykey.md
      - data/database/sqlserver.md
      - data/database/sqlsession.md
      - data/database/sqlview.md
    - 'Cascade':
      - data/cascaded/index.md
      - data/cascaded/stored_query.md
      - data/cascaded/wfs.md
      - data/cascaded/wms.md
      - data/cascaded/wmts.md
    - 'Application Schema':
      - data/app-schema/index.md
      - data/app-schema/app-schema-resolution.md
      - data/app-schema/complex-features.md
      - data/app-schema/configuration.md
      - data/app-schema/cql-functions.md
      - data/app-schema/data-access-integration.md
      - data/app-schema/data-stores.md
      - data/app-schema/feature-chaining.md
      - data/app-schema/installation.md
      - data/app-schema/joining.md
      - data/app-schema/mapping-file.md
      - data/app-schema/mongo-tutorial.md
      - data/app-schema/polymorphism.md
      - data/app-schema/property-interpolation.md
      - data/app-schema/secondary-namespaces.md
      - data/app-schema/solr-tutorial.md
      - data/app-schema/supported-gml-versions.md
      - data/app-schema/tutorial.md
      - data/app-schema/wfs-2.0-support.md
      - data/app-schema/wfs-service-settings.md
      - data/app-schema/wms-support.md