name: Advengers assemble

on:
  pull_request

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Xmx756m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            jdk: 11
            dist: 'temurin'
    steps:
    - uses: actions/checkout@v4
      with:
        # 500 commits, set to 0 to get all
        fetch-depth: 500
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: ${{ matrix.dist }}
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5
    - name: Maven repository caching
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: gs-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gs-${{ runner.os }}-maven-
    - name: Remove SNAPSHOT jars from repository before build  # optimization to avoid -U on each step
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
    - name: Build GeoServer modules and extensions
      run: |
        mvn -B -ntp -T3 -DskipTests -Dspotless.apply.skip=true -Prelease -f src/pom.xml install
    - name: Package GeoServer modules and extensions
      run: |
        mvn -B -ntp -f src/pom.xml assembly:single -nsu -N
    - name: Build community modules
      run: |
        mvn -B -ntp -T3 -DskipTests -Dspotless.apply.skip=true -Prelease -PcommunityRelease -f src/community/pom.xml install
    - name: Package community modules
      run:  |
        mvn -B -ntp -f src/community/pom.xml assembly:single -nsu -N
    - name: Remove SNAPSHOT jars from repository after build
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
