name: Docs CI

on:
  pull_request:
    paths:
      - doc/**
      - src/pom.xml

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Xmx512m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          sphinx
          requests
    - name: Build docs
      run: mvn -f doc/en -ntp -B compile
    - name: Check index.html
      run: |
        if test ! -f doc/en/target/user/html/index.html; then
          echo sphinx-build did not generate user/html/index.html >&2
          exit 1
        fi

  docs-zhcn:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          sphinx
          requests
    - name: Build docs
      run: mvn -f doc/zhCN -ntp -B compile
    - name: Check index.html
      run: |
        if test ! -f doc/zhCN/target/user/html/index.html; then
          echo sphinx-build did not generate user/html/index.html >&2
          exit 1
        fi
